### ISSUE TITLE
How to print in grayscale

### ISSUE THREAD

**Issue by kingkongkai** [pklaus/brother_ql_web#42]
Is there a way to print labels with the gray scale values intact, or does brother_ql only support black and white thresholding? My label printer will print fine in grayscale when other software is used, but then there is the usual issue of paper size.

**Comment by FriedrichFroebel** [comment]
Are you sure that this issue should be reported against this repository with the web interface instead of the *brother_ql* base repository? According to the docs at https://github.com/pklaus/brother_ql/blob/56cf4394ad750346c6b664821ccd7489ec140dae/brother_ql/raster.py#L219-L221, I would assume that the answer is no for now. This seems to be given by https://github.com/pklaus/brother_ql/blob/56cf4394ad750346c6b664821ccd7489ec140dae/brother_ql/conversion.py#L154-L157 as well, which handles the actual conversion for the simple case with only black-on-white tape.

Skimming through the command reference at http://download.brother.com/welcome/docp000678/cv_qlseries_eng_raster_600.pdf and the code of *brother_ql*, I am not sure whether grayscale printing could be supported.

**Comment by kingkongkai** [comment]
Oops, no, I'm sorry, I meant to post this in the base repository indeed. Too many tabs open.

I should have mentioned, I am using a QL-800. This model is not covered in that command reference, but it does print grayscale when using other software.

**Comment by FriedrichFroebel** [comment]
Having a quick skim through https://download.brother.com/welcome/docp100278/cv_ql800_eng_raster_101.pdf, I could not find any helpful reference on this as well.

**Comment by kingkongkai** [comment]
I apologize, I didn't know what dithering was before now. That's actually the functionality I was looking for, which happened automatically when printing a gray scale image with other software.

There seems to be another issue though, regarding input/output error, which I only started getting on the QL-800. But I'll file a separate issue for that later.
