### ISSUE TITLE
Red text supported in brother_ql but not brother_ql_web

### ISSUE THREAD

**Issue by hairychris** [pklaus/brother_ql_web#7]
I had a quick go at hacking this in but got a problem converting L to RGB in Pillow. I will have another go at it next weekend, in the interim do you have any specific ideas about how this should work?

**Comment by pavittr** [comment]
I also got stuck on this, my printer just froze due to bad input and I had to hack the call to the Raster class. I got something a bit more complete working tonight on a fork: https://github.com/pavittr/brother_ql_web . I only tested this locally on a Mac so there may be Windows/Linux/Docker bugs I haven't seen.

One issue I couldn't see an obvious solution to is that you can only choose either all red or all black. Given the printer appears to need to know the difference even if you only print in black, I wanted a way to say "This cartridge is red and black, but only print in black". My two thoughts were:

1. Another parameter - easy but possibly not very clean
2. Allow the colour to vary - would be nice but may be overkill for what the app does.

Appreciate any advice before I raise a PR.

**Comment by hairychris** [comment]
Great work!

How would option 2 work? Is there some way of getting the printer to say which colour roll it has detected because I couldn't find one.

**Comment by Andhaa** [comment]
Same issue, with QL810W. I try changing roll to 62mm red/black/white, still just get a red blinking LED on my printer. If I do --red option in brother_ql it the printer prints perfectly.

Regarding autodetect I quickly glanced over the command references from brothers dev site, and it does not look like its supported over raster, possibly over esc/p?

**Comment by pklaus** [comment]
Thank you all for reporting this. I prepared a fix for this. Will push in a couple of seconds...

**Comment by pklaus** [comment]
For now, I was lazy: If the black/red/white label is selected, the text will be red. It would be nice if this could be configured for each individual label you want to print. But for now it's like this.

**Comment by hairychris** [comment]
Thanks for implementing this. Like you say it would be nice to be able to configure on a per label basis or even use black / red in different parts of the same label. I've not played with the CLI much but is it possible to do this if you create your own image currently?
